name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Use Node 16.x
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
          cache: "yarn"

      # Install Packages
      - name: Install Packages
        run: yarn install

      # Run Lint
      - name: Run Lint
        run: yarn lint

      # Run Unit Tests
      - name: Run Unit Tests
        run: yarn test

      # Publish to NPM
      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
