name: Test, Lint and Build

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Use Node 16.x
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      # Install Packages
      - name: Install Packages
        run: yarn install

      # Run Lint
      - name: Run Lint
        run: yarn lint

      # Run Unit Tests
      - name: Run Unit Tests
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: tests
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Use Node 16.x
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      # Install Packages
      - name: Install Packages
        run: yarn install

      # Run Build
      - name: Run Build
        run: yarn build

      # Create NPM Package
      - name: Create NPM Package
        run: yarn pack

      # Archive NMP Package
      - name: Archive NPM Package
        uses: actions/upload-artifact@v2
        with:
          name: archive
          path: "*.tgz"
